name: calculator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  keyboard_actions: ^3.4.5
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dxe.png
    - assets/pq_prime.png
    - assets/equation_one.png
    - assets/equation_two.png
    - assets/form_totiete.png
    - assets/equation_tree.png
    - assets/equation_four.png

  fonts:
    - family: FontCustom
      fonts:
        - asset: fonts/Merry.ttf
